# Generated by packaging/homebrew/render_formula.py - do not edit by hand.
#
# Installs the prebuilt release archive rather than compiling: the build needs
# CMake and a C++20 toolchain, and a `brew install` that takes two minutes to
# compile a 1 MB binary is a worse experience than one that takes two seconds.
class ComputerControl < Formula
  desc "Desktop and mobile-simulator automation, as an MCP server"
  homepage "https://github.com/minhnd410/computer-control"
  version "0.2.0"
  license "MIT"

  on_macos do
    depends_on macos: :monterey # ScreenCaptureKit needs 12.3+
    on_arm do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.2.0/computer-control-macos-arm64.tar.gz"
      sha256 "057fdaa7871f4fa9d95ea45716be72c648ce60b5672ba183299acc583c7e137c"
    end
    on_intel do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.2.0/computer-control-macos-x86_64.tar.gz"
      sha256 "37c92f21dd2f42bb098d02ff2f3c1175c772ee677054086912c13af3b5db8138"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.2.0/computer-control-linux-x86_64.tar.gz"
      sha256 "86d357fdaa1a63dfd1746a8f4eba1966eb06f5db2cc758a09c13b12331b71a67"
    end
    on_arm do
      odie "No prebuilt archive for Linux on arm64 yet. Build from source: " \
           "https://github.com/minhnd410/computer-control/blob/main/docs/install.md"
    end
  end

  def install
    bin.install "computer-control-mcp"
  end

  def caveats
    on_macos do
      <<~TEXT
        computer-control needs two macOS permissions:
          Accessibility                    input and the accessibility tree
          Screen & System Audio Recording  screenshots

        Grant them, then check:
          computer-control-mcp --request-permissions
          computer-control-mcp --doctor

        A binary launched from a terminal inherits that terminal's grant and
        never appears in System Settings on its own. If element queries come
        back empty, --doctor explains why and what to add.
      TEXT
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/computer-control-mcp --version")
    # A capability report needs a window server, which the sandbox lacks, so
    # only the argument-free paths run here.
    system bin/"computer-control-mcp", "--list-tools"
  end
end
