# Generated by packaging/homebrew/render_formula.py - do not edit by hand.
#
# Installs the prebuilt release archive rather than compiling: the build needs
# CMake and a C++20 toolchain, and a `brew install` that takes two minutes to
# compile a 1 MB binary is a worse experience than one that takes two seconds.
class ComputerControl < Formula
  desc "Desktop and mobile-simulator automation, as an MCP server"
  homepage "https://github.com/minhnd410/computer-control"
  version "0.7.3"
  license "MIT"

  on_macos do
    depends_on macos: :monterey # ScreenCaptureKit needs 12.3+
    on_arm do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.7.3/computer-control-macos-arm64.tar.gz"
      sha256 "5889b44ccf2d895271638d90fae392aff17f1087452bba5988781cd9e2316492"
    end
    on_intel do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.7.3/computer-control-macos-x86_64.tar.gz"
      sha256 "91ed2f866d5a1062efbc8f5c2db5657e2b0ed7ab855542c8f1e4993b0988357c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/minhnd410/computer-control/releases/download/v0.7.3/computer-control-linux-x86_64.tar.gz"
      sha256 "1860f96b16ce06d9a39ab5c1e8c0f89533d88df9f0face3d949079c7ec1b198a"
    end
    on_arm do
      odie "No prebuilt archive for Linux on arm64 yet. Build from source: " \
           "https://github.com/minhnd410/computer-control/blob/main/docs/install.md"
    end
  end

  def install
    bin.install "computer-control-mcp"
  end

  def caveats
    <<~TEXT
      Finish setting up by running:

        computer-control-mcp setup

      It finds the MCP clients on this machine, asks which should get
      computer-control, writes the config for the ones you pick, and then
      requests the OS permissions it needs. Run it again any time.

      Homebrew cannot prompt during install, which is why this is a separate
      command rather than something that already happened.
    TEXT
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/computer-control-mcp --version")
    # A capability report needs a window server, which the sandbox lacks, so
    # only the argument-free paths run here.
    system bin/"computer-control-mcp", "--list-tools"
  end
end
